# ?????????????????????????????????????????
# APPLICATION
# ?????????????????????????????????????????
spring.application.name=api-gateway
server.port=8080

# ?????????????????????????????????????????
# SPRING CLOUD GATEWAY ROUTES
#
# Each route has 3 parts:
# id        ? unique name for this route
# uri       ? where to forward the request
# predicates ? what URL pattern triggers this route
# ?????????????????????????????????????????

# Route 1 ? metadata-service
# All /api/instances/** calls go to metadata-service
spring.cloud.gateway.mvc.routes[0].id=metadata-service
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/instances/**

# Route 2 ? lifecycle-service
# All /api/lifecycle/** calls go to lifecycle-service
spring.cloud.gateway.mvc.routes[1].id=lifecycle-service
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/lifecycle/**

# Route 3 ? provisioning-service
# All /api/provisioning/** calls go to provisioning-service
spring.cloud.gateway.mvc.routes[2].id=provisioning-service
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/provisioning/**

# ?????????????????????????????????????????
# ACTUATOR
# ?????????????????????????????????????????
management.endpoints.web.exposure.include=health,info