# ?????????????????????????????????????????
# APPLICATION
# ?????????????????????????????????????????
spring.application.name=lifecycle-service
server.port=8082

# ?????????????????????????????????????????
# METADATA SERVICE URL
# lifecycle-service calls metadata-service
# to read and update instance state
# ?????????????????????????????????????????
metadata.service.url=http://localhost:8081

# ?????????????????????????????????????????
# ACTUATOR
# ?????????????????????????????????????????
management.endpoints.web.exposure.include=health,info